### ISSUE TITLE
Iframe pulling other links from my website, not just the gravity form - lead pages

### ISSUE THREAD

**Issue by jmu289** [cedaro/gravity-forms-iframe#41]
Hi,

I'm having a weird issues that i've been asking gravity forms and leadpages about and they can't figure it out.

I'm trying to add a gravity form to a leadpage. According to leadpages, this is doable:
https://support.leadpages.net/hc/en-us/articles/203521930-Can-I-Insert-A-Survey-Gravity-Forms-Or-Other-Into-A-Leadpages-Page-

But, when I paste IFrame into lead pages it shows the gravity form AND the header menu links of my website

See for example, these two test leadpages:
- https://opt-insignup.leadpages.co/practice-exam-test/ 
- https://opt-insignup.leadpages.co/practice-exam-test-2/ 

Notice how underneath the gravity form there is some hyperlinks for "home", "about us", etc... these are all the links from my top menu bar on my website (see associatepi.com)

The gravity form is SUPPOSED to look like it does on this page http://associatepi.com/cpcu-and-api-practice-exam-downloads/ 

When I reached out to lead pages they said:
"It looks like you currently have iFrame code for the full URL you provided. Because it's for the full site, that iFrame code includes the additional links like "Home", "About Us", ect. that are being pulled from the page and onto your form in Leadpages. You'll either need an iFrame code of just the form or to host the form on a plain website without those links and get the iFrame code for that." 

Do you know how I can get an "iFrame code of just the form" per leadpages suggestion? 

Or have you seen this issue before and do you have any suggestions on how to fix this?

Thanks!

This is the IFrame i'm using:
iframe src='//associatepi.com/gfembed/?f=1' width='100%' height='500' frameBorder='0' class='gfiframe'

**Comment by bradyvercher** [comment]
It looks like that's due to your theme printing a responsive menu in the `wp_footer` action.

The [template for displaying Gravity Forms](https://github.com/cedaro/gravity-forms-iframe/blob/develop/templates/gravity-forms-iframe.php#L18) in an iframe has to use `wp_footer()` to output all the scripts and styles needed to make a form work, but that may also include scripts, styles, and other output from the theme or other plugins that hook into `wp_footer`.

Your best bet is to manually remove any actions adding extra output in the iframe template.

**Comment by jmu289** [comment]
Got it, thank you for the quick help!
