### ISSUE TITLE
Submit Form Using AJAX

### ISSUE THREAD

**Issue by andywarren** [cedaro/gravity-forms-iframe#43]
Maybe I'm not looking in the right spot, but I'm trying to submit the form using AJAX, and cannot seem to accomplish this. I see `<?php GFFormDisplay::print_form_scripts( $form, false ); // ajax = false ?>` in the template file I have in my child theme, and have tried changing `false` to `true`, but that still does not submit the form using AJAX.

What am I doing wrong here?

**Comment by bradyvercher** [comment]
Hi @andywarren, is there a reason you need AJAX if the form is being loaded in an iframe?

I haven't tested AJAX myself, but the call to `gravity_form()` in that template [has an argument to enable AJAX](https://www.gravityhelp.com/documentation/article/embedding-a-form/#function-call) as well, so you may need to give that a shot. It should probably look something like this:

`gravity_form( $form_id, $display_title, $display_description, false, null, true );`

**Comment by andywarren** [comment]
Hi @bradyvercher, thanks for the reply. We were looking to use AJAX due to a tracking script needing to be placed on the parent page through Google Tag Manager, and we're trying to find a way to do that. We found a possible solution in GTM that watches for AJAX requests, and then fires a tag based on that, so we wanted to try it. We're having trouble getting a tag to fire based on the form submission on that page due to it being in an iframe.

Maybe a little off topic for this support request, but would you know if we could possible just include GTM in the iframe template file and track the submissions that way?

**Comment by bradyvercher** [comment]
Hmm, I'm not sure GTM is going to see the AJAX request in the iframe, either. You're also probably going to run into issues with the form and parent page being on different domains, so I'm not sure adding the GTM snippet directly to the template will work.

If they are on different domains and you can't get that to work, you would probably need to use the `postMessage` API to send events to the parent window kinda like this:

In the iframe template, listen for the Gravity Form submission, then send an event to the parent window:
```html
<script>
// Send a message to the parent window.
window.parent.postMessage({
	event: 'submit'
}, '*' );
</script>
```
In the parent window, listen for events from the iframe and if it does what you want, use the GTM API to log it:
```html
<script>
window.addEventListener( 'message', function( e ) {
	// Skip if the origin doesn't match the iframe.
	if ( e.origin !== 'https://iframe.domain' ) {
		//return;
	}

	// Trigger a GTM event?
	console.log( e.data )
});
</script>
```

The only other option I can come up with off the top of my head is to use the [GTM API](https://developers.google.com/tag-manager/api/v1/) on the form server to submit the data you need.

**Comment by andywarren** [comment]
@bradyvercher I've been working on getting this implemented, but ran into some issues. I started a question on StackOverflow that you can see [here](http://stackoverflow.com/questions/41069705/postmessage-function-runs-repeatedly-without-a-message-being-sent).

It lead to a discussion that can be seen [here](http://chat.stackoverflow.com/rooms/130262/discussion-between-andywarren-and-alexander-omara).

What I've discovered is that there is a `postmessage()` in the iframe plugin that is repeatedly posting the iframe size, and that in turn is causing your possible solution from above to not work.

Would you know if there is a way to adjust the plugin's `postMessage()` to not repeatedly post the iframe size?

**Comment by bradyvercher** [comment]
That message is needed to resize the iframe to ensure its contents are always visible without enabling scrollbars. It might be possible to prevent it from continually polling like it does now, but in any case, it's always going to send multiple messages and there's always the possibility that another script could be sending messages, so you need to account for that.

In the parent window, you should be checking the messages that your listener receives to ensure it's one you want to process. Usually you'd do that by assigning it some sort of unique identifier when you send it (kinda like prefixing things in WordPress). If you do `console.log( e.data )` instead of a string like `Submitted`, you should be able to tell a difference between the size messages and your submit message (using my example, your 'submit' message should have an `event` property with `submit` as the value, but the data can be anything you want).

Like any data received from a unknown source, there are security implications, so you do want to be sure the data you're receiving is of the expected format and is safe to use -- that's partly why I added that origin check in the example.

I've been planning to adjust the format of that size message to make it easier to parse, but it shouldn't effect how you handle things on your end.

**Comment by andywarren** [comment]
@bradyvercher Thanks so much for your help on this and getting me in the right direction. I now have a working example of this doing exactly what I need it to do, which is fire a tag on the parent when the iframed form is submitted.

For future reference to anyone needing it, here is "my" solution: http://stackoverflow.com/a/41105317/1076613

*Notice the parenthesis around "my"...thanks again @bradyvercher, and to the people on StackOverflow!

**Comment by bradyvercher** [comment]
No problem, @andywarren! Glad to hear you were able to get it working the way you needed.
