### ISSUE TITLE
Issue with embedding Gravity form on Clickfunnels page - Can you help please?

### ISSUE THREAD

**Issue by ElmarSandyck** [cedaro/gravity-forms-iframe#61]
Hello,

I've used your Gravity Forms add-on. It partially solved my problem.

I installed your plugin (gravity-froms-iframe-master) on my Wordpress site, I generated the embed code and put it on my Clickfunnels page.
Now the Gravity Form is displayed on my Clickfunnels page and it works fine, but aside from the Gravity form also other parts from my Wordpress site are now displayed on my Clickfunnels page, and this is not the purpose of course.

You can see it on this page: https://fijnafslanken.be/ultrasculptor-gelaat (this is a Clickfunnels page published on my website)
When you click on the yellow button on that page a pop-up will open. Inside the pop-up you'll see 2 forms, the second form from the top is the Gravity form (I still need to remove the top one). But then below the 2nd form you'll see a big white X, a big white messenger icon, another big white X, a Facebook Like-box, etc... Also, when people click on the yellow "Verzenden" button, they are not sent to the thank you page, which is important.

How can the extra things (the white big X, etc...) be removed from the pop-up window? And how can I make sure that people are sent to my thank you page? I guess there have to be made some adjustments to the embed code.

Can you please take a look at this and give me news? This would help me a lot.

Thanks a lot and best regards,

Elmar Sandyck

**Comment by bradyvercher** [comment]
Hi @ElmarSandyck, the template used for displaying the form calls [`wp_footer()`](https://github.com/cedaro/gravity-forms-iframe/blob/develop/templates/gravity-forms-iframe.php#L18) to print scripts and styles that are required for Gravity Forms to look and function correctly. The theme and other plugins can hook into the `wp_footer` action to print their own assets, which may also be included when viewing an embedded form.

Unfortunately, there's not much that can be done about that form the plugin itself. You would need to figure out what is printing those extra elements and disable them yourself.

As for redirecting to a page on submission, that's not really possible since the form is embedded in an iframe.
